### ISSUE TITLE
Proofreading feito com carinho

### ISSUE THREAD

**Issue by aquelemiguel** [ieeeupsb/workshop-distributed-systems#1]
- Welcome to this workshop's wiki! This is where you **you** can see the exercises you're supposed to be doing.
- Where is the name **associated** with the client you want to send a PM to.
- How **to** prepare private data exchanges
- If you made it this far **then** boy howdy, congratulations!
- Right now there's nothing really distributed systems-related that you **can't** do.

**Comment by Areadrill** [comment]
Fixed, thanks ❤️
